## Exercise 5
Use the `pandas.crosstab` to find solution to the problem below.

| |Credit Card|Cash|Mobile Pay|Total|
|---|---|---|---|---|
|Under $50|85|120|45|250|
|$50-$100|110|40|50|200|
|Over $100|40|5|5|50|
|Total|235|165|100|500|


a. What is the probability that a randomly selected transaction is over $100? 

b. What is the probability that a transction uses Cash?

c. What is the probability that a transaction is between $50-$100 AND uses Mobile Pay?

d. If a transaction is under $50, what is the probability it was paid with Credit Card?

e. If a transaction uses Cash, what is the probability it is under $50?

(Answers: a. 0.10 b. 0.33 c. 0.10 d. 0.34 e. 0.727  )

In [4]:
#Solution here
import pandas as pd
data = {
    'Amount_status' : ['Under $50']*250 + ['$50 - $100']*200 + ['Over $100']*50,
    'Payment_status' :(['Credit Card']*85 + ['Cash']*120 + ['Mobile Pay'] * 45 +
                       ['Credit Card']*110 + ['Cash']*40 + ['Mobile Pay'] * 50 +
                       ['Credit Card']*40 + ['Cash']*5 + ['Mobile Pay'] * 5)
}
df = pd.DataFrame(data)
# Create contingency table
table = pd.crosstab(df['Amount_status'], df['Payment_status'], margins=True)
print(table)

total = table.loc['All','All']
print(" ")



Payment_status  Cash  Credit Card  Mobile Pay  All
Amount_status                                     
$50 - $100        40          110          50  200
Over $100          5           40           5   50
Under $50        120           85          45  250
All              165          235         100  500
 


### (a) Probability that a transaction is over \$100

$
P(\text{Over 100}) = \frac{50}{500} = 0.10
$

In [39]:
# probability that a randomly selected transaction is over $100
print(f"P(Over $100) = {table.loc['Over $100','All']/total:.2f}")

P(Over $100) = 0.10


### (b) Probability that a transaction uses Cash

$
P(\text{Cash}) = \frac{165}{500} = 0.33
$

In [11]:
# probability that a transction uses Cash?
print("P(Cash) =",table.loc['All','Cash']/total)

P(Cash) = 0.33


### (c) Probability that a transaction is between \$50–\$100 AND uses Mobile Pay

$
P(\text{50–100} \cap \text{Mobile Pay}) = \frac{50}{500} = 0.10
$

In [40]:
#probability that a transaction is between  $50-$100 AND uses Mobile Pay
print(f"P($50-$100 and Mobile Pay) =  {table.loc['$50 - $100','Mobile Pay']/total:.2f}")

P($50-$100 and Mobile Pay) =  0.10


### (d) If a transaction is under \$50, probability it was paid with Credit Card

$
P(\text{Credit Card} \mid \text{Under 50}) = \frac{85}{250} = 0.34
$

In [30]:
#If a transaction is under $50, probability that a transaction is paid with Credit Card
print("P(Credit Card given Under $50) =", table.loc['Under $50','Credit Card']/table.loc['Under $50','All'])

P(Credit Card given Under $50) = 0.34


### (e) If a transaction uses Cash, probability it is under \$50

$
P(\text{Under 50} \mid \text{Cash}) = \frac{120}{165} \approx 0.727
$

In [37]:
# If a transaction uses Cash, the probability that is under $50?
print(f"P(Under $50 given Cash) = { table.loc['Under $50','Cash']/table.loc['All','Cash']:.3f}")

P(Under $50 given Cash) = 0.727
